---
apiVersion: v1
kind: Secret
metadata:
  name: myapp-auth-2
  namespace: flux-system
stringData:
  .dockerconfigjson: '{"auths":{"ghcr.io":{"username":"dwijad","password":"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","auth":"ZHdpamFkOmdocF9ES3NQYlpvT3RLSWcxZjVidlVyb1ZtcTlKbEtDWkI0RHVqUU0="}}}'
type: kubernetes.io/dockerconfigjson

