---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: flux-image-policy-demo
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: flux-image-repo-demo
  policy:
    semver:
      range: 1.0.x
