---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: image-demo-helm-repo
  namespace: flux-system
spec:
  interval: 10s
  provider: generic
  type: default
  url: https://github.com/Dwijad/helm-example
  secretRef:
    name: bearer-token-auth