---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: image-demo-helm-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nginx-charts
      interval: 5m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: image-demo-helm-repo
  interval: 10m0s
  valuesFrom:
  - kind: ConfigMap
    name: image-demo-helm-cm
